export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const ORDER_LIST = 'ORDER_LIST';
export const ORDER_LIST_START = 'ORDER_LIST_START';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED';
